---
#- hosts: *
#  become: no
#  tasks:
- name: Gather the package facts
  package_facts:
    manager: auto
- name: Print the package facts
  debug:
    var: ansible_facts.packages
- name: Copy ansible facts to a file
  copy:
    content: "{{ ansible_facts.packages }}"
    dest: '{{ directory_cmdb }}/{{ ansible_hostname }}_packages.json'
  delegate_to: localhost
- name: Get facts
  ansible.builtin.debug:
    var: ansible_facts
- name: Copy ansible facts to a file
  copy:
    content: "{{ ansible_facts}}"
    dest: '{{ directory_cmdb }}/{{ ansible_hostname}}_facts.json'
  delegate_to: localhost
